# Generated by Django 5.0 on 2024-02-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomimage',
            name='image_url',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
