# Generated by Django 5.0 on 2024-02-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogen', '0002_alter_randomimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomimage',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
