# Generated by Django 5.0 on 2024-02-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogen', '0003_alter_randomimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=12)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
