# Generated by Django 5.0 on 2024-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogen', '0004_sessionzip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionzip',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='sessionzip',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='sessionzip',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='sessionzip',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='sessionzip',
            name='image5',
        ),
        migrations.AddField(
            model_name='sessionzip',
            name='file_download',
            field=models.FileField(default='', upload_to='zip_files/'),
        ),
    ]
