# Generated by Django 5.0 on 2024-02-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogen', '0005_remove_sessionzip_image1_remove_sessionzip_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomImage',
        ),
    ]
